name: GROMACS Simulation Workflow

on:
  workflow_dispatch:

jobs:
  gromacs-simulation:
    runs-on: ubuntu-latest
    container: 
      image: gromacs/gromacs:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Run GROMACS simulation script
      run: |
        chmod +x ./scripts/gmx.sh
        ./scripts/gmx.sh
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: ions
        path: ./results/ions.gro
          
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: em
        path: ./results/em.gro
          
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: nvt
        path: ./results/nvt.gro

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: npt
        path: ./results/npt.gro
          
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: md
        path: ./results/md.gro

