name: GROMACS Simulation Workflow

on:
  workflow_dispatch:

jobs:
  gromacs-simulation:
    runs-on: ubuntu-latest
    container: 
      image: gromacs/gromacs:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up GROMACS environment
      run: |
        apt-get update && apt-get install -y gnuplot

    - name: Run GROMACS simulation script
      run: bash /scripts/gmx.sh
      env:
        GMX_MAXBACKUP: -1 # Prevents overwriting files
